### ISSUE TITLE
kdb+/q 32-bit (No Fee - Non Commercial) no longer available

### ISSUE THREAD

**Issue by lcsrodriguez** [andymans/docker-kdb#4]
### Description of the issue

Hi,

Thank you for your work.
I've recently seen that KX had terminated their 32-bit version of kdb+/q (No Fee - Non Commercial), and it is no longer possible to download a zip file, needed in your work.

As newer version of 32-bit source won't be released and KX specifies this:

> Kdb+ on demand 64 bit personal edition is for your personal, non-commercial use. It may be used on up to 2 computers, to a maximum of 24 cores per computer. It **cannot be used on any cloud**, only your local environment. **Kdb+ on demand requires an always on internet connection to operate**.

for their 64-bit version, do you have any alternative for an operational Docker image for kdb+, or any upgrade to your work ?

Thank you.

### Screenshots 
<img width="800" alt="image" src="https://user-images.githubusercontent.com/36009581/187837982-1a76ade3-c0bb-4408-a962-a425c900035f.png">

### References
- https://kx.com/developers/download-licenses/
- https://kx.com/64bit-on-demand-personal-edition/

**Comment by andymans** [comment]
Hi,

I did find (though it was some years back) some website where it was possible to download a copy of the 32-bit executable (perhaps version 3.3, or version 3.2). I believe it was related to this announcement:

https://www.anaconda.com/blog/anaconda-and-kx-systems-partner-to-deliver-kdb-database-system-and-related-machine-learning-libraries

At the time you could get a download of the Anaconda product (multiple python scripts plus a KDB+ executable). It may not currently be there...but the "wayback machine" might help you there.

I'm afraid that's as much as I know.
